force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>You work at the Pet Shop!</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grooming_Appointment__c/Grooming_Appointment__c.object-meta.xml
<CustomObject>
    <description>Appointment to clean up your animal!</description>
    <label>Grooming Appointment</label>
    <nameField>
        <label>Appointment Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grooming Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grooming_Appointment__c/fields/Appointment_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Time__c</fullName>
    <label>Appointment Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Grooming_Appointment__c/fields/Current_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Current_Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grooming_Appointment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The employee that will be conducting the grooming appointment.</description>
    <inlineHelpText>The employee that will be conducting the grooming appointment.</inlineHelpText>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Grooming Appointments</relationshipLabel>
    <relationshipName>Grooming_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grooming_Appointment__c/fields/Grooming_Types__c.field-meta.xml
<CustomField>
    <fullName>Grooming_Types__c</fullName>
    <label>Grooming Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nail Trimming</fullName>
            </value>
            <value>
                <fullName>Bathing</fullName>
            </value>
            <value>
                <fullName>Teeth Cleaning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grooming_Appointment__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Pet in the Appointment</inlineHelpText>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Grooming Appointments</relationshipLabel>
    <relationshipName>Grooming_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grooming_Appointment__c/fields/Satisfaction_Rating__c.field-meta.xml
<CustomField>
    <fullName>Satisfaction_Rating__c</fullName>
    <label>Satisfaction Rating</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for Client Rating</fullName>
            </value>
            <value>
                <fullName>Bad</fullName>
            </value>
            <value>
                <fullName>Decent</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Amazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grooming_Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GroomingScheduleController.cls
public class GroomingScheduleController {
    
	@auraEnabled
    public static List<Grooming_Appointment__c> getAppts(String dateRange, List<String> selectedApptTypes){
        
        System.debug(dateRange);
        
        String baseQuery = 'SELECT Id, Name, Appointment_Time__c, Client_Phone__c, Current_Appointment__c, Employee__c, '
        				+ 'Grooming_Types__c, Pet__c, Satisfaction_Rating__c, Status__c FROM Grooming_Appointment__c '
                    	+ 'WHERE Grooming_Types__c includes ';
        
		String qry = baseQuery + buildQuery.mplOr(selectedApptTypes);
        
        if (dateRange=='All'){
        }
        else if (dateRange=='Today'){
        	qry += ' AND Appointment_Time__c = TODAY';
        }
        else if (dateRange=='Upcoming'){
            qry += ' AND Appointment_Time__c >= TODAY';
        }
        
        
        
        qry += ' ORDER BY Appointment_Time__c ASC';
        
        System.debug(qry);
        
        /*
		return [SELECT Id, Name, Appointment_Time__c, Client_Phone__c, Current_Appointment__c, Employee__c, 
                      Grooming_Types__c, Pet__c, Satisfaction_Rating__c, Status__c FROM Grooming_Appointment__c 
                      WHERE Grooming_Types__c = :selectedApptTypes];
		*/
        
        return Database.query(qry);
    }
}