force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>You work at the Pet Shop!</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grooming_Appointment__c/Grooming_Appointment__c.object-meta.xml
<CustomObject>
    <description>Appointment to clean up your animal!</description>
    <label>Grooming Appointment</label>
    <nameField>
        <label>Appointment Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grooming Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grooming_Appointment__c/fields/Appointment_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Time__c</fullName>
    <label>Appointment Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Grooming_Appointment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The employee that will be conducting the grooming appointment.</description>
    <inlineHelpText>The employee that will be conducting the grooming appointment.</inlineHelpText>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Grooming Appointments</relationshipLabel>
    <relationshipName>Grooming_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grooming_Appointment__c/fields/Grooming_Types__c.field-meta.xml
<CustomField>
    <fullName>Grooming_Types__c</fullName>
    <label>Grooming Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nail Trimming</fullName>
            </value>
            <value>
                <fullName>Bathing</fullName>
            </value>
            <value>
                <fullName>Teeth Cleaning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GroomingScheduleControllerTest.cls
@isTest
private class GroomingScheduleControllerTest {
	

    @testSetup
    private static void buildTestData(){
        Employee__c testEmployee = new Employee__c(Name='Test');
        insert testEmployee;
        
        List<Grooming_Appointment__c> testAppts = new List<Grooming_Appointment__c>();
        
        for (integer iii=-100; iii<100; ++iii){
            Grooming_Appointment__c testAppt = new Grooming_Appointment__c(Employee__c = testEmployee.Id, 
                                                                           Appointment_Time__c = Date.today()+iii,
                                                                           Client_Phone__c = '5555555555');
            if ((iii==0) || (iii==1)){
                System.debug('TEST DATA: made new Teeth Cleaning appt.' + testAppt.Appointment_Time__c);
                testAppt.Grooming_Types__c = 'Teeth Cleaning';
            }
            else if (iii<0)
                testAppt.Grooming_Types__c = 'Bathing';
            else if (iii>1)
                testAppt.Grooming_Types__c = 'Bathing;Nail Trimming';
            
            testAppts.add(testAppt);
        }
        
        insert testAppts;
    }

    
    @isTest
    private static void testToday(){
        List<String> apptTypes = new List<String> {'Teeth Cleaning'};
        List<Grooming_Appointment__c> apptTest = GroomingScheduleController.getAppts('Today', apptTypes);
        System.assertEquals(1, apptTest.size());
        
        List<String> apptTypes2 = new List<String> {'Bathing'};
        List<Grooming_Appointment__c> apptTest2 = GroomingScheduleController.getAppts('Today', apptTypes2);
        System.assertEquals(0, apptTest2.size());
    }
    
    @isTest
    private static void testUpcoming(){
        List<String> apptTypes = new List<String> {'Bathing'};
        List<Grooming_Appointment__c> apptTest = GroomingScheduleController.getAppts('Upcoming', apptTypes);
        System.assertEquals(98, apptTest.size());
    }
    
    @isTest
    private static void testAll(){
        List<String> apptTypes = new List<String> {'Bathing','Teeth Cleaning'};
        List<Grooming_Appointment__c> apptTest = GroomingScheduleController.getAppts('All', apptTypes);
        System.assertEquals(200, apptTest.size());
    }
}