force-app/main/default/objects/Reward_Points__c/Reward_Points__c.object-meta.xml
<CustomObject>
    <description>An object for the storage of reward points for specific email phones and address</description>
    <label>Reward Points</label>
    <nameField>
        <displayFormat>Rewards-{0000}</displayFormat>
        <label>Rewards Account</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reward Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_Points__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <inlineHelpText>Please enter an address for shipping</inlineHelpText>
    <label>Address</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reward_Points__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestClassDylan.cls
@isTest
private class TestClassDylan {
    @isTest static void myRewardPointsTest(){
        Reward_Points__c rp = new Reward_Points__c(
            Email__c='jake@gmail.com', Address__c='123 Tough Street',
            Customer_Name__c='jake', Points__c=5000);        
        insert rp;
        try{          
            RewardController.updatePoints(5000, rp.id);  
        }catch (exception e){
            System.debug(e.getMessage());            
        }
        System.debug('rp.Points__c: ' + rp.Points__c);
        Reward_Points__c results = RewardController.getRewardPoints(rp.Email__c);        
        System.assertEquals(5000, results.Points__c);
    }
}