force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <description>Adopt a new pal today!</description>
    <label>Adoption</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Animal_Age__c.field-meta.xml
<CustomField>
    <fullName>Animal_Age__c</fullName>
    <label>Animal Age</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Animal_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puppy (5-8 months old)</fullName>
            </value>
            <value>
                <fullName>Kitten (5-8 months old)</fullName>
            </value>
            <value>
                <fullName>Junior (1-2 years old)</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Egg (0-65 days)</fullName>
            </value>
            <value>
                <fullName>Juvenile (0-10 years)</fullName>
            </value>
            <value>
                <fullName>Adolescent (10-20 years)</fullName>
            </value>
            <value>
                <fullName>Adult (20+ years)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Animal_Type__c.field-meta.xml
<CustomField>
    <fullName>Animal_Type__c</fullName>
    <label>Animal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dog</fullName>
            </value>
            <value>
                <fullName>Cat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Still Residing</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Animal_Age__c.field-meta.xml
<CustomField>
    <fullName>Animal_Age__c</fullName>
    <label>Animal Age</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Animal_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puppy (5-8 months old)</fullName>
            </value>
            <value>
                <fullName>Kitten (5-8 months old)</fullName>
            </value>
            <value>
                <fullName>Junior (1-2 years old)</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Egg (0-65 days)</fullName>
            </value>
            <value>
                <fullName>Juvenile (0-10 years)</fullName>
            </value>
            <value>
                <fullName>Adolescent (10-20 years)</fullName>
            </value>
            <value>
                <fullName>Adult (20+ years)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Animal_Type__c.field-meta.xml
<CustomField>
    <fullName>Animal_Type__c</fullName>
    <label>Animal Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/recordTypes/Pet.recordType-meta.xml
<RecordType>
    <fullName>Pet</fullName>
    <active>true</active>
    <label>Pet</label>
</RecordType>

force-app/main/default/globalValueSets/Animal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Alligator</fullName>
    </customValue>
    <customValue>
        <fullName>Hamster</fullName>
        <isActive>false</isActive>
        <label>Hamster</label>
    </customValue>
    <customValue>
        <fullName>Bird</fullName>
        <isActive>false</isActive>
        <label>Bird</label>
    </customValue>
    <masterLabel>Animal Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DisplayAdoptions_CC.cls
public with sharing class DisplayAdoptions_CC {
    public String pet {
        get {
            return pet;
        }
        set {
            pet = value;
        }
    }

    // Indicates whether records were found
    public Boolean matches {
        get {
            return ( (pets != null) && (pets.size() != 0) );
        }
        set;
    }

    public Boolean searched {get; set;}                             // Indicates whether search has been done
    public ApexPages.StandardSetController setStandCon { get; set; }     // Standard Set Controller

    // Constructor
    public DisplayAdoptions_CC() {
        searched=false;
    }

    // List of Contacts displayed on the page
    public List<Adoption__c> pets {
        get {
            if (setStandCon != null ) {
                return (List<Adoption__c>)setStandCon.getRecords();
            } else {
                return null;
            }
        }
        set;
    }

    // Action method initiated by user
    public void Search() {
        System.debug(pet);
        if (String.isNotBlank(pet)) {
            List<Adoption__c> pets = [SELECT Id, Name, Pet__r.Name, Animal_Type__C, Animal_Age__c, Status__c From Adoption__c 
                                                                            WHERE Pet__r.Name LIKE :pet
                                                                            OR Animal_Type__c LIKE :pet];
            setStandCon = new ApexPages.StandardSetController(pets);
            setStandCon.setPageNumber(1);
            setStandCon.setPageSize(10);

            searched = true;
        }else {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please enter search text'));
        } 
    }
}