force-app/main/default/objects/Guide__c/Guide__c.object-meta.xml
<CustomObject>
    <description>Records for grooming and other guides.</description>
    <label>Guide</label>
    <nameField>
        <label>Guide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guide__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this page should be available to the guide.</description>
    <inlineHelpText>Check to enable this page for the guide.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Guide__c/fields/For_Guides__c.field-meta.xml
<CustomField>
    <fullName>For_Guides__c</fullName>
    <description>The guides this page is for.</description>
    <inlineHelpText>The guides this page is intended for.</inlineHelpText>
    <label>For Guides</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Guides</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guide__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <description>Set of instructions for a page in the grooming guide.</description>
    <inlineHelpText>Instructions for this step.</inlineHelpText>
    <label>Instructions</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Guide__c/fields/Instructions_HTML__c.field-meta.xml
<CustomField>
    <fullName>Instructions_HTML__c</fullName>
    <description>HTML-formatted instructions for this page - for display in grooming guide aura page.</description>
    <inlineHelpText>HTML-formatted instructions for this page - for display in the grooming guide aura app.</inlineHelpText>
    <label>Instructions (HTML)</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Guide__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>This article&apos;s intended place in the guide it is a part of.</description>
    <inlineHelpText>The article&apos;s intended place in its guide; affects the order pages are displayed in on the web component.</inlineHelpText>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guide__c/fields/Page_Title__c.field-meta.xml
<CustomField>
    <fullName>Page_Title__c</fullName>
    <description>Title for this page.</description>
    <inlineHelpText>Guide page title</inlineHelpText>
    <label>Page Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Guides.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Grooming</fullName>
    </customValue>
    <customValue>
        <fullName>Alligator</fullName>
    </customValue>
    <description>List of guides available in this org.</description>
    <masterLabel>Guides</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GuideControllerTest.cls
@isTest
private class GuideControllerTest {
    
    @isTest
    private static void dataRetrievalSingleTest(){
		Guide__c guide = new Guide__c(Name='name', Instructions__c='instructions', Page_Title__c='title', Active__c=true, 
                                          Instructions_HTML__c='html', Order__c = 0, For_Guides__c='Grooming');
        insert guide;
        
        List<Guide__c> singlePageGuideTest = new List<Guide__c>();
        singlePageGuideTest = GuideController.getGuides();
        
        System.assertEquals(1, singlePageGuideTest.size());
    }
    

    @isTest
    private static void dataRetrievalBulkTest(){
        List<Guide__c> testGuides = new List<Guide__c>();
        for (integer iii=0; iii<300; ++iii){
            String num = String.valueOf(iii);
            Guide__c guide = new Guide__c(Name=num, Instructions__c='instructions '+num, Page_Title__c='title '+num, Active__c=true, 
                                          Instructions_HTML__c='html '+num, Order__c = iii, For_Guides__c='Grooming');
            testGuides.add(guide);
        }
        insert testGuides;
        
        List<Guide__c> guideTest = new List<Guide__c>();
        guideTest = GuideController.getGuides();
        
        System.assertEquals(300, guideTest.size());
    }
}