force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <description>Stuff to use for a Grooming Appointment!</description>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Item_Cost__c.field-meta.xml
<CustomField>
    <fullName>Item_Cost__c</fullName>
    <label>Item Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Toys</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Stock_Count__c.field-meta.xml
<CustomField>
    <fullName>Stock_Count__c</fullName>
    <label>Stock Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Stock_Count__c.field-meta.xml
<CustomField>
    <fullName>Stock_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stock Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InventoryTest.cls
@isTest
private class InventoryTest {
    
    @testSetup
    private static void loadTestData() {
        List<Product2> testInv = new List<Product2>();
        for(Integer i=0;i<4;i++) {
            testInv.add(new Product2(Name = 'testInvName'+i, Family = 'Food'));
        }
        insert testInv;    
    }
    
    @isTest
    private static void testSearchText() {
        List<Product2> pResults = Inventory_CX_Aura.search('testInv');
        System.debug(pResults.size());
        System.assertEquals(pResults.size(), 4);     
    }
    
    /*
     @isTest
    private static void testMatches() {
        Inventory_CX inventory = new Inventory_CX();
        inventory.matches = false;
        System.assertEquals(false, inventory.matches);    
    }

    @isTest
    private static void testSearched() {
        Inventory_CX inventory = new Inventory_CX();
        inventory.searched =true;
        System.assertEquals(true, inventory.searched);    
    }

    @isTest
    private static void testInventories() {
        Inventory_CX inventory = new Inventory_CX();
        List<Inventory__c> testInv = [SELECT Name, Item_Cost__c, Item_Type__c, Stock_Count__c FROM Inventory__c];
        inventory.inventories =testInv;
        System.assertNotEquals(testInv, inventory.inventories);    
    }

    @isTest
    private static void testInventoryCX() {
        Inventory_CX inventory = new Inventory_CX();   
    }

    @isTest
    private static void testSearchMethod() {
        Inventory_CX inventory = new Inventory_CX();
        inventory.searchText = 'testInvName';
        inventory.Search();
        System.assertEquals(true, inventory.searched);    
    }

    @isTest
    private static void testSearchMethodFalse() {
        Inventory_CX inventory = new Inventory_CX();
        inventory.searchText = 't';
        inventory.Search();
        System.assertEquals(true, ApexPages.hasMessages(ApexPages.Severity.ERROR));    
    }
    */

}