force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <description>Stuff to use for a Grooming Appointment!</description>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Stock_Count__c.field-meta.xml
<CustomField>
    <fullName>Stock_Count__c</fullName>
    <label>Stock Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Unit Price</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_A_Service__c.field-meta.xml
<CustomField>
    <fullName>Is_A_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Denotes whether service is a product</inlineHelpText>
    <label>Is A Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Stock_Count__c.field-meta.xml
<CustomField>
    <fullName>Stock_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stock Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Inventory_CX_Aura.cls
public with sharing class Inventory_CX_Aura {
    @AuraEnabled
    public static String searchText {
        get {
            return searchText;
        }
        set {
            searchtext = value;
        }
    }

    public Boolean matches {
        get {
            return ( (inventories != null) && (inventories.size() != 0) );
        }
        set;
    }

    public static Boolean searched {get; set;}                             
    public ApexPages.StandardSetController setCon { get; set; }     

    
    public Inventory_CX_Aura() {
        searched=false;
    }

    public List<Inventory__c> inventories {
        get {
            if (setCon != null ) {
                return (List<Inventory__c>)setCon.getRecords();
            } else {
                return null;
            }
        }
        set;
    }

    @AuraEnabled
    public static List<sObject> search(String searchText) {

        if(String.isBlank(searchText)){
            List<sObject> inventories = [SELECT Name, Family, Stock_Count__c, Currency__c 
                                         FROM Product2 WHERE Is_A_Service__c = false];
            return inventories;
        }
        if (String.isNotBlank(searchText) && searchtext.length() > 1) {
            
            List<sObject> inventories = [FIND :searchText
                                    IN ALL FIELDS
                                    RETURNING Product2 (Name, Family, Stock_Count__c, Currency__c WHERE Is_A_Service__c = false)][0];

            //setCon = new ApexPages.StandardSetController(inventories);
            //setCon.setPageNumber(1);
            //setCon.setPageSize(10);

            searched = true;
            return inventories;
        } /*else {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,
                                                    'Please enter search text at least one characters long'));
                                                    
        }*/
        return null;
        
        
    }
}